name: Django Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: Hrdip@2010
          POSTGRES_DB: test_db
          POSTGRES_PORT: 5432
          HOST: 172.19.0.7
        ports:
          - 5432/tcp

    steps:
    - uses: actions/checkout@v3
    - name: Setup Docker-Compose
      run: docker-compose up -d
    - name: Run Tests
      run: docker exec backend sh -c "flake8 && pytest ."
