name: Django Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: Hrdip@2010
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Setup Docker-Compose
      run: docker-compose up -d
    - name: Run migrations
      working-directory: ./core
      run: python manage.py migrate
    - name: Run Tests
      run: docker exec backend sh -c "flake8 && pytest ."
