name: Django Project Test

on:
  push:
    branches: [ "sss" ]
  pull_request:
    branches: [ "msss" ]

jobs:

  Test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: Hrdip@2010
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    env: 
      HOST: 127.0.0.1
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Docker-Compose
      run: docker-compose -f docker-compose-stage.yml up -d
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run migrations
      working-directory: ./core
      run: python manage.py migrate
    
    - name: Run Tests
      run: docker exec backend sh -c "flake8 && pytest ."


  Deploy:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    name: Deploy
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - name: Chekout the files
      uses: actions/checkout@v3
    
    - name: Deploy to AWS Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        REMOTE_HOST: ${{secrets.HOST_DNS}}
        REMOTE_USER: ${{secrets.USERNAME}}
        TARGET: ${{secrets.TARGET_DIR}}

    - name: Executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        username: ${{secrets.USERNAME}}
        host: ${{secrets.HOST_DNS}}
        key: ${{secrets.EC2_SSH_KEY}}
        script: |
          cd ${{secrets.PROJECT_PATH}}
          docker-compose -f docker-compose-prod.yml stop
          git pull
          docker-compose -f docker-compose-prod.yml restart
          


